# Generated by Django 3.2.6 on 2023-07-09 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
    ]
